apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
    track: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: web
        tier: frontend
        track: stable
    spec:
      containers:
      - name: web
        image: gcr.io/formidable-gate-221816/web
        ports:
        - containerPort: 8080
        env:
        - name: DEMO_GREETING
          value: "Hello from the environment"