apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: web
  selector:
    app: web
    tier: frontend